# Generated by Django 2.0.2 on 2018-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180912_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
